<?php

namespace ContainerHnAc6wP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_7o4OZzCService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.7o4OZzC' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.7o4OZzC'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Controller\\Admin\\DashboardController::index' => ['privates', '.service_locator.UI5KYeY.App\\Controller\\Admin\\DashboardController::index()', 'getDashboardControllerindexService', true],
            'App\\Controller\\Admin\\LandingPageController::index' => ['privates', '.service_locator..Ycl0yH.App\\Controller\\Admin\\LandingPageController::index()', 'getLandingPageControllerindexService', true],
            'App\\Controller\\Admin\\LeadController::index' => ['privates', '.service_locator.s9yYaZE.App\\Controller\\Admin\\LeadController::index()', 'getLeadControllerindexService', true],
            'App\\Controller\\Admin\\PartnerController::index' => ['privates', '.service_locator.WfhCzcs.App\\Controller\\Admin\\PartnerController::index()', 'getPartnerControllerindexService', true],
            'App\\Controller\\Admin\\PartnerController::new' => ['privates', '.service_locator.5o8bSyK.App\\Controller\\Admin\\PartnerController::new()', 'getPartnerControllernewService', true],
            'App\\Controller\\Admin\\PartnerController::edit' => ['privates', '.service_locator.3OW3Jic.App\\Controller\\Admin\\PartnerController::edit()', 'getPartnerControllereditService', true],
            'App\\Controller\\Admin\\PartnerController::toggleStatus' => ['privates', '.service_locator.1ajaxh1.App\\Controller\\Admin\\PartnerController::toggleStatus()', 'getPartnerControllertoggleStatusService', true],
            'App\\Controller\\Admin\\PartnerController::delete' => ['privates', '.service_locator.1ajaxh1.App\\Controller\\Admin\\PartnerController::delete()', 'getPartnerControllerdeleteService', true],
            'App\\Controller\\AppCustomAuthenticatorController::login' => ['privates', '.service_locator.0MQaTBY.App\\Controller\\AppCustomAuthenticatorController::login()', 'getAppCustomAuthenticatorControllerloginService', true],
            'App\\Controller\\Partner\\DashboardController::index' => ['privates', '.service_locator.s9yYaZE.App\\Controller\\Partner\\DashboardController::index()', 'getDashboardControllerindex2Service', true],
            'App\\Controller\\Partner\\LandingPageController::index' => ['privates', '.service_locator..Ycl0yH.App\\Controller\\Partner\\LandingPageController::index()', 'getLandingPageControllerindex2Service', true],
            'App\\Controller\\Partner\\LandingPageController::edit' => ['privates', '.service_locator.iuvQFu3.App\\Controller\\Partner\\LandingPageController::edit()', 'getLandingPageControllereditService', true],
            'App\\Controller\\Public\\LandingPageController::show' => ['privates', '.service_locator.JrHs_Fc.App\\Controller\\Public\\LandingPageController::show()', 'getLandingPageControllershowService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.0MQaTBY.App\\Controller\\SecurityController::login()', 'getSecurityControllerloginService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Controller\\Admin\\DashboardController:index' => ['privates', '.service_locator.UI5KYeY.App\\Controller\\Admin\\DashboardController::index()', 'getDashboardControllerindexService', true],
            'App\\Controller\\Admin\\LandingPageController:index' => ['privates', '.service_locator..Ycl0yH.App\\Controller\\Admin\\LandingPageController::index()', 'getLandingPageControllerindexService', true],
            'App\\Controller\\Admin\\LeadController:index' => ['privates', '.service_locator.s9yYaZE.App\\Controller\\Admin\\LeadController::index()', 'getLeadControllerindexService', true],
            'App\\Controller\\Admin\\PartnerController:index' => ['privates', '.service_locator.WfhCzcs.App\\Controller\\Admin\\PartnerController::index()', 'getPartnerControllerindexService', true],
            'App\\Controller\\Admin\\PartnerController:new' => ['privates', '.service_locator.5o8bSyK.App\\Controller\\Admin\\PartnerController::new()', 'getPartnerControllernewService', true],
            'App\\Controller\\Admin\\PartnerController:edit' => ['privates', '.service_locator.3OW3Jic.App\\Controller\\Admin\\PartnerController::edit()', 'getPartnerControllereditService', true],
            'App\\Controller\\Admin\\PartnerController:toggleStatus' => ['privates', '.service_locator.1ajaxh1.App\\Controller\\Admin\\PartnerController::toggleStatus()', 'getPartnerControllertoggleStatusService', true],
            'App\\Controller\\Admin\\PartnerController:delete' => ['privates', '.service_locator.1ajaxh1.App\\Controller\\Admin\\PartnerController::delete()', 'getPartnerControllerdeleteService', true],
            'App\\Controller\\AppCustomAuthenticatorController:login' => ['privates', '.service_locator.0MQaTBY.App\\Controller\\AppCustomAuthenticatorController::login()', 'getAppCustomAuthenticatorControllerloginService', true],
            'App\\Controller\\Partner\\DashboardController:index' => ['privates', '.service_locator.s9yYaZE.App\\Controller\\Partner\\DashboardController::index()', 'getDashboardControllerindex2Service', true],
            'App\\Controller\\Partner\\LandingPageController:index' => ['privates', '.service_locator..Ycl0yH.App\\Controller\\Partner\\LandingPageController::index()', 'getLandingPageControllerindex2Service', true],
            'App\\Controller\\Partner\\LandingPageController:edit' => ['privates', '.service_locator.iuvQFu3.App\\Controller\\Partner\\LandingPageController::edit()', 'getLandingPageControllereditService', true],
            'App\\Controller\\Public\\LandingPageController:show' => ['privates', '.service_locator.JrHs_Fc.App\\Controller\\Public\\LandingPageController::show()', 'getLandingPageControllershowService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.0MQaTBY.App\\Controller\\SecurityController::login()', 'getSecurityControllerloginService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\Admin\\DashboardController::index' => '?',
            'App\\Controller\\Admin\\LandingPageController::index' => '?',
            'App\\Controller\\Admin\\LeadController::index' => '?',
            'App\\Controller\\Admin\\PartnerController::index' => '?',
            'App\\Controller\\Admin\\PartnerController::new' => '?',
            'App\\Controller\\Admin\\PartnerController::edit' => '?',
            'App\\Controller\\Admin\\PartnerController::toggleStatus' => '?',
            'App\\Controller\\Admin\\PartnerController::delete' => '?',
            'App\\Controller\\AppCustomAuthenticatorController::login' => '?',
            'App\\Controller\\Partner\\DashboardController::index' => '?',
            'App\\Controller\\Partner\\LandingPageController::index' => '?',
            'App\\Controller\\Partner\\LandingPageController::edit' => '?',
            'App\\Controller\\Public\\LandingPageController::show' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\Admin\\DashboardController:index' => '?',
            'App\\Controller\\Admin\\LandingPageController:index' => '?',
            'App\\Controller\\Admin\\LeadController:index' => '?',
            'App\\Controller\\Admin\\PartnerController:index' => '?',
            'App\\Controller\\Admin\\PartnerController:new' => '?',
            'App\\Controller\\Admin\\PartnerController:edit' => '?',
            'App\\Controller\\Admin\\PartnerController:toggleStatus' => '?',
            'App\\Controller\\Admin\\PartnerController:delete' => '?',
            'App\\Controller\\AppCustomAuthenticatorController:login' => '?',
            'App\\Controller\\Partner\\DashboardController:index' => '?',
            'App\\Controller\\Partner\\LandingPageController:index' => '?',
            'App\\Controller\\Partner\\LandingPageController:edit' => '?',
            'App\\Controller\\Public\\LandingPageController:show' => '?',
            'App\\Controller\\SecurityController:login' => '?',
        ]);
    }
}
