<?php

namespace ContainerHnAc6wP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDashboardControllerindex2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.s9yYaZE.App\Controller\Partner\DashboardController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.s9yYaZE.App\\Controller\\Partner\\DashboardController::index()'] = ($container->privates['.service_locator.s9yYaZE'] ?? $container->load('get_ServiceLocator_S9yYaZEService'))->withContext('App\\Controller\\Partner\\DashboardController::index()', $container);
    }
}
