<?php

namespace ContainerHnAc6wP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDashboardControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.UI5KYeY.App\Controller\Admin\DashboardController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.UI5KYeY.App\\Controller\\Admin\\DashboardController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'partnerRepository' => ['privates', 'App\\Repository\\PartnerRepository', 'getPartnerRepositoryService', true],
            'landingPageRepository' => ['privates', 'App\\Repository\\LandingPageRepository', 'getLandingPageRepositoryService', true],
            'leadRepository' => ['privates', 'App\\Repository\\LeadRepository', 'getLeadRepositoryService', true],
        ], [
            'partnerRepository' => 'App\\Repository\\PartnerRepository',
            'landingPageRepository' => 'App\\Repository\\LandingPageRepository',
            'leadRepository' => 'App\\Repository\\LeadRepository',
        ]))->withContext('App\\Controller\\Admin\\DashboardController::index()', $container);
    }
}
