<?php

namespace ContainerHnAc6wP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLandingPageController2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Partner\LandingPageController' shared autowired service.
     *
     * @return \App\Controller\Partner\LandingPageController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'framework-bundle'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'AbstractController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'Partner'.\DIRECTORY_SEPARATOR.'LandingPageController.php';

        $container->services['App\\Controller\\Partner\\LandingPageController'] = $instance = new \App\Controller\Partner\LandingPageController();

        $instance->setContainer(($container->privates['.service_locator.TJNRSaV'] ?? $container->load('get_ServiceLocator_TJNRSaVService'))->withContext('App\\Controller\\Partner\\LandingPageController', $container));

        return $instance;
    }
}
