<?php

namespace ContainerHnAc6wP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPartnerControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.3OW3Jic.App\Controller\Admin\PartnerController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.3OW3Jic.App\\Controller\\Admin\\PartnerController::edit()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'partner' => ['privates', '.errored..service_locator.3OW3Jic.App\\Entity\\Partner', NULL, 'Cannot autowire service ".service_locator.3OW3Jic": it needs an instance of "App\\Entity\\Partner" but this type has been excluded because it\'s a Doctrine entity.'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'passwordHasher' => ['privates', 'security.user_password_hasher', 'getSecurity_UserPasswordHasherService', true],
        ], [
            'partner' => 'App\\Entity\\Partner',
            'entityManager' => '?',
            'passwordHasher' => '?',
        ]))->withContext('App\\Controller\\Admin\\PartnerController::edit()', $container);
    }
}
