<?php

namespace ContainerHnAc6wP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPartnerControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.WfhCzcs.App\Controller\Admin\PartnerController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.WfhCzcs.App\\Controller\\Admin\\PartnerController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'partnerRepository' => ['privates', 'App\\Repository\\PartnerRepository', 'getPartnerRepositoryService', true],
        ], [
            'partnerRepository' => 'App\\Repository\\PartnerRepository',
        ]))->withContext('App\\Controller\\Admin\\PartnerController::index()', $container);
    }
}
