<?php

namespace ContainerHnAc6wP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPartnerControllernewService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.5o8bSyK.App\Controller\Admin\PartnerController::new()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.5o8bSyK.App\\Controller\\Admin\\PartnerController::new()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'passwordHasher' => ['privates', 'security.user_password_hasher', 'getSecurity_UserPasswordHasherService', true],
            'landingTemplateRepository' => ['privates', 'App\\Repository\\LandingTemplateRepository', 'getLandingTemplateRepositoryService', true],
        ], [
            'entityManager' => '?',
            'passwordHasher' => '?',
            'landingTemplateRepository' => 'App\\Repository\\LandingTemplateRepository',
        ]))->withContext('App\\Controller\\Admin\\PartnerController::new()', $container);
    }
}
