<?php

namespace ContainerMM8GkRP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAppCustomAuthenticatorControllerloginService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.0MQaTBY.App\Controller\AppCustomAuthenticatorController::login()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.0MQaTBY.App\\Controller\\AppCustomAuthenticatorController::login()'] = ($container->privates['.service_locator.0MQaTBY'] ?? $container->load('get_ServiceLocator_0MQaTBYService'))->withContext('App\\Controller\\AppCustomAuthenticatorController::login()', $container);
    }
}
