<?php

namespace ContainerMM8GkRP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLandingPageControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.iuvQFu3.App\Controller\Partner\LandingPageController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.iuvQFu3.App\\Controller\\Partner\\LandingPageController::edit()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'landingPage' => ['privates', '.errored..service_locator.iuvQFu3.App\\Entity\\LandingPage', NULL, 'Cannot autowire service ".service_locator.iuvQFu3": it needs an instance of "App\\Entity\\LandingPage" but this type has been excluded because it\'s a Doctrine entity.'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
        ], [
            'landingPage' => 'App\\Entity\\LandingPage',
            'entityManager' => '?',
        ]))->withContext('App\\Controller\\Partner\\LandingPageController::edit()', $container);
    }
}
