<?php

namespace ContainerMM8GkRP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLandingPageControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.JrHs_Fc.App\Controller\Public\LandingPageController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.JrHs_Fc.App\\Controller\\Public\\LandingPageController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'landingPageRepository' => ['privates', 'App\\Repository\\LandingPageRepository', 'getLandingPageRepositoryService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
        ], [
            'landingPageRepository' => 'App\\Repository\\LandingPageRepository',
            'entityManager' => '?',
        ]))->withContext('App\\Controller\\Public\\LandingPageController::show()', $container);
    }
}
