<?php

namespace ContainerMM8GkRP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLandingPageControllerindex2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator..Ycl0yH.App\Controller\Partner\LandingPageController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator..Ycl0yH.App\\Controller\\Partner\\LandingPageController::index()'] = ($container->privates['.service_locator..Ycl0yH'] ?? $container->load('get_ServiceLocator__Ycl0yHService'))->withContext('App\\Controller\\Partner\\LandingPageController::index()', $container);
    }
}
