<?php

namespace ContainerMM8GkRP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPartnerControllertoggleStatusService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.1ajaxh1.App\Controller\Admin\PartnerController::toggleStatus()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.1ajaxh1.App\\Controller\\Admin\\PartnerController::toggleStatus()'] = ($container->privates['.service_locator.1ajaxh1'] ?? $container->load('get_ServiceLocator_1ajaxh1Service'))->withContext('App\\Controller\\Admin\\PartnerController::toggleStatus()', $container);
    }
}
